apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: acs-qe 
  janus-idp.io/tekton: acs-qe
  backstage.io/kubernetes-id: acs-qe
  backstage.io/kubernetes-namespace: oc-ci-e2e 
  app.kubernetes.io/part-of: acs-qe
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  