apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: acs-qe
  janus-idp.io/tekton: acs-qe
  backstage.io/kubernetes-id: acs-qe
  backstage.io/kubernetes-namespace: oc-ci-e2e 
  app.kubernetes.io/part-of: acs-qe
resources: 
- deployment.yaml
- route.yaml
- service.yaml
